var Die = function () {
    this.value = null;
    this.div = null;
    this.insert = function () {
        this.div = document.createElement("div");
        this.div.className = "dieDesign";
        this.roll();
        document.getElementById('mainDiv').appendChild(this.div);
    }
    this.roll = function () {
        var num = Math.floor(Math.random() * 6) + 1;
        this.value = num;
        this.div.innerHTML = num;
    }
}
var dice = []; //has to be in the global scope
var numberSum = []; //code for sumDice

function addDie() {
    var dieDesign = new Die();
    var someDiv = document.createElement("div");
    someDiv.className = "dieDesign";
    dieDesign.div = someDiv;
    dieDesign.roll();
    document.getElementById('mainDiv').appendChild(someDiv);
    dice.push(dieDesign);
}

function rollDice() {
    for (var i = 0; i < dice.length; i++) {
        dice[i].roll();
    }
}

function sumDice() {
    //need to push all the numbers that were generated by the this.roll function
    //into the numberSum array, then add up those numbers in the array. HOW?
    // num.push(numberSum); //code for sumDice - needs to be incorporated 
    var diceTotal = 0;
    for (var i = 0, sum = 0; i < numberSum.length; sum += numberSum[i++]);
    alert("The sum of the dice is " + diceTotal);
}